//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz_Co2HomeServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_Co2HomeSaversEntities1 : DbContext
    {
        public db_Co2HomeSaversEntities1()
            : base("name=db_Co2HomeSaversEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AffilaiteLink> tbl_AffilaiteLink { get; set; }
        public virtual DbSet<tbl_Barbecue> tbl_Barbecue { get; set; }
        public virtual DbSet<tbl_Bathtubr> tbl_Bathtubr { get; set; }
        public virtual DbSet<tbl_Bidet> tbl_Bidet { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Computer> tbl_Computer { get; set; }
        public virtual DbSet<tbl_Cooktop> tbl_Cooktop { get; set; }
        public virtual DbSet<tbl_Dishwashere> tbl_Dishwashere { get; set; }
        public virtual DbSet<tbl_Dryer> tbl_Dryer { get; set; }
        public virtual DbSet<tbl_Electriccarcharger> tbl_Electriccarcharger { get; set; }
        public virtual DbSet<tbl_Faucet> tbl_Faucet { get; set; }
        public virtual DbSet<tbl_Fireplace> tbl_Fireplace { get; set; }
        public virtual DbSet<tbl_Freezer> tbl_Freezer { get; set; }
        public virtual DbSet<tbl_Furnance> tbl_Furnance { get; set; }
        public virtual DbSet<tbl_GamingConsole> tbl_GamingConsole { get; set; }
        public virtual DbSet<tbl_GasDryer> tbl_GasDryer { get; set; }
        public virtual DbSet<tbl_GasOven> tbl_GasOven { get; set; }
        public virtual DbSet<tbl_Generator> tbl_Generator { get; set; }
        public virtual DbSet<tbl_healthiestlightbulbs> tbl_healthiestlightbulbs { get; set; }
        public virtual DbSet<tbl_Humidifier> tbl_Humidifier { get; set; }
        public virtual DbSet<tbl_Jacuzzi> tbl_Jacuzzi { get; set; }
        public virtual DbSet<tbl_Laptop> tbl_Laptop { get; set; }
        public virtual DbSet<tbl_Lawnsprinklersystem> tbl_Lawnsprinklersystem { get; set; }
        public virtual DbSet<tbl_Microwave> tbl_Microwave { get; set; }
        public virtual DbSet<tbl_Modem> tbl_Modem { get; set; }
        public virtual DbSet<tbl_Outdoorsprinklersystem> tbl_Outdoorsprinklersystem { get; set; }
        public virtual DbSet<tbl_Oven> tbl_Oven { get; set; }
        public virtual DbSet<tbl_Pool> tbl_Pool { get; set; }
        public virtual DbSet<tbl_Programmablethermostat> tbl_Programmablethermostat { get; set; }
        public virtual DbSet<tbl_Refrigilator> tbl_Refrigilator { get; set; }
        public virtual DbSet<tbl_ResutImages> tbl_ResutImages { get; set; }
        public virtual DbSet<tbl_Router> tbl_Router { get; set; }
        public virtual DbSet<tbl_Shower> tbl_Shower { get; set; }
        public virtual DbSet<tbl_Showerhead> tbl_Showerhead { get; set; }
        public virtual DbSet<tbl_Sink> tbl_Sink { get; set; }
        public virtual DbSet<tbl_Smartphone> tbl_Smartphone { get; set; }
        public virtual DbSet<tbl_Smartpowerstrip> tbl_Smartpowerstrip { get; set; }
        public virtual DbSet<tbl_SmartSpeaker> tbl_SmartSpeaker { get; set; }
        public virtual DbSet<tbl_Solarpanels> tbl_Solarpanels { get; set; }
        public virtual DbSet<tbl_Stove> tbl_Stove { get; set; }
        public virtual DbSet<tbl_Television> tbl_Television { get; set; }
        public virtual DbSet<tbl_Toilet> tbl_Toilet { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_WashingMachine> tbl_WashingMachine { get; set; }
        public virtual DbSet<tbl_WaterAC> tbl_WaterAC { get; set; }
        public virtual DbSet<tbl_Waterdispenser> tbl_Waterdispenser { get; set; }
        public virtual DbSet<tbl_WaterHeater> tbl_WaterHeater { get; set; }
        public virtual DbSet<tbl_WRefrigilator> tbl_WRefrigilator { get; set; }
    
        public virtual ObjectResult<string> InsertUsernameAndReturn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertUsernameAndReturn");
        }
    
        public virtual int InsertRefrigilator(string username, Nullable<int> noOfRefrigilators)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var noOfRefrigilatorsParameter = noOfRefrigilators.HasValue ?
                new ObjectParameter("NoOfRefrigilators", noOfRefrigilators) :
                new ObjectParameter("NoOfRefrigilators", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertRefrigilator", usernameParameter, noOfRefrigilatorsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectRefrigilatorsByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectRefrigilatorsByUsernme", usernameParameter);
        }
    
        public virtual ObjectResult<GetLowestTotalWattsRecords_Result> GetLowestTotalWattsRecords(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLowestTotalWattsRecords_Result>("GetLowestTotalWattsRecords", usernameParameter);
        }
    
        public virtual ObjectResult<GetSecondLowestTotalWattsRecords_Result> GetSecondLowestTotalWattsRecords(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSecondLowestTotalWattsRecords_Result>("GetSecondLowestTotalWattsRecords", usernameParameter);
        }
    
        public virtual ObjectResult<GetThirdHighestTotalWattsRecords_Result> GetThirdHighestTotalWattsRecords(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThirdHighestTotalWattsRecords_Result>("GetThirdHighestTotalWattsRecords", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords_Result> GetWattsRecords(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords_Result>("GetWattsRecords", usernameParameter);
        }
    
        public virtual int UpdateRefrigeratorTips(string username, string newTip1Value, string newTip2Value, string newTip3Value)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var newTip1ValueParameter = newTip1Value != null ?
                new ObjectParameter("NewTip1Value", newTip1Value) :
                new ObjectParameter("NewTip1Value", typeof(string));
    
            var newTip2ValueParameter = newTip2Value != null ?
                new ObjectParameter("NewTip2Value", newTip2Value) :
                new ObjectParameter("NewTip2Value", typeof(string));
    
            var newTip3ValueParameter = newTip3Value != null ?
                new ObjectParameter("NewTip3Value", newTip3Value) :
                new ObjectParameter("NewTip3Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateRefrigeratorTips", usernameParameter, newTip1ValueParameter, newTip2ValueParameter, newTip3ValueParameter);
        }
    
        public virtual int UpdateRefrigilatorTips(string username, string newTip1, string newTip2, string newTip3)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var newTip1Parameter = newTip1 != null ?
                new ObjectParameter("NewTip1", newTip1) :
                new ObjectParameter("NewTip1", typeof(string));
    
            var newTip2Parameter = newTip2 != null ?
                new ObjectParameter("NewTip2", newTip2) :
                new ObjectParameter("NewTip2", typeof(string));
    
            var newTip3Parameter = newTip3 != null ?
                new ObjectParameter("NewTip3", newTip3) :
                new ObjectParameter("NewTip3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateRefrigilatorTips", usernameParameter, newTip1Parameter, newTip2Parameter, newTip3Parameter);
        }
    
        public virtual int UpdateTotalWattsForUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectFreezersByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectFreezersByUsernme", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectDryerByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectDryerByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser2(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser2", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser3(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser3", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectMicrowavesByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectMicrowavesByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser4(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser4", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectOvensByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectOvensByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser5(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser5", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectStovesByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectStovesByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser6(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser6", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectWashingMachineByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectWashingMachineByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser7(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser7", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectDishwasherByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectDishwasherByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser8(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser8", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords1_Result> GetWattsRecords1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords1_Result>("GetWattsRecords1", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords2_Result> GetWattsRecords2(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords2_Result>("GetWattsRecords2", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords3_Result> GetWattsRecords3(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords3_Result>("GetWattsRecords3", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords4_Result> GetWattsRecords4(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords4_Result>("GetWattsRecords4", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords5_Result> GetWattsRecords5(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords5_Result>("GetWattsRecords5", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectWaterHeaterByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectWaterHeaterByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser9(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser9", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectTelevisionByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectTelevisionByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForTV(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForTV", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectComputerByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectComputerByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForComputer(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForComputer", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectLaptopByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectLaptopByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForLaptop(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForLaptop", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectSmartphoneByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectSmartphoneByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForSmartphone(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForSmartphone", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectSmartSpeakerByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectSmartSpeakerByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForSmartSpeaker(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForSmartSpeaker", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectGamingConsoleByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectGamingConsoleByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForGamingConsole(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForGamingConsole", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectRouterByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectRouterByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForRouter(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForRouter", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectModemByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectModemByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForModem(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForModem", usernameParameter);
        }
    
        public virtual int SelectBathtubByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectBathtubByUsernme", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectShowerByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectShowerByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForBathtub(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForBathtub", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForShower(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForShower", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectSinkByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectSinkByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForSink(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForSink", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectToiletByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectToiletByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForToilet(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForToilet", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectWaterdispenserByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectWaterdispenserByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForWaterdispenser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForWaterdispenser", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectHumidifierByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectHumidifierByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForHumidifier(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForHumidifier", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectOutdoorsprinklersystemByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectOutdoorsprinklersystemByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForOutdoorsprinklersystem(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForOutdoorsprinklersystem", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectPoolByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectPoolByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForPool(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForPool", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectJacuzziByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectJacuzziByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForJacuzzi(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForJacuzzi", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectBidetByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectBidetByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForBidet(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForBidet", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectShowerheadByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectShowerheadByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForShowerhead(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForShowerhead", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectFaucetByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectFaucetByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForFaucet(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForFaucet", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectLawnsprinklersystemByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectLawnsprinklersystemByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForLawnsprinklersystem(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForLawnsprinklersystem", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectWRefrigilatorByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectWRefrigilatorByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForWRefrigilator(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForWRefrigilator", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectCooktopByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectCooktopByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForCooktop(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForCooktop", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectGasDryerByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectGasDryerByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForGasDryer(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForGasDryer", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectBarbecueByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectBarbecueByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForBarbecue(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForBarbecue", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectGeneratorByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectGeneratorByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForGenerator(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForGenerator", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectGasOvenByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectGasOvenByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForGasOven(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForGasOven", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectProgrammablethermostatByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectProgrammablethermostatByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForProgrammablethermostat(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForProgrammablethermostat", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectSolarpanelsByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectSolarpanelsByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForSolarpanels(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForSolarpanels", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectSmartpowerstripByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectSmartpowerstripByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForSmartpowerstrip(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForSmartpowerstrip", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectElectriccarchargerByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectElectriccarchargerByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForElectriccarcharger(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForElectriccarcharger", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelecthealthiestlightbulbsByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelecthealthiestlightbulbsByUsernme", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectWaterACByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectWaterACByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForWaterAC(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForWaterAC", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectFurnanceByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectFurnanceByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForFurnance(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForFurnance", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectFireplaceByUsernme(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectFireplaceByUsernme", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForFireplace(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForFireplace", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForAlternateElectricityAppliances_Result> GetWattsRecordsForAlternateElectricityAppliances(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForAlternateElectricityAppliances_Result>("GetWattsRecordsForAlternateElectricityAppliances", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForGasAppliances_Result> GetWattsRecordsForGasAppliances(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForGasAppliances_Result>("GetWattsRecordsForGasAppliances", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHeatingAndCooling_Result> GetWattsRecordsForHeatingAndCooling(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHeatingAndCooling_Result>("GetWattsRecordsForHeatingAndCooling", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHomeEntertainment_Result> GetWattsRecordsForHomeEntertainment(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHomeEntertainment_Result>("GetWattsRecordsForHomeEntertainment", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForWaterAppliances_Result> GetWattsRecordsForWaterAppliances(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForWaterAppliances_Result>("GetWattsRecordsForWaterAppliances", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords6_Result> GetWattsRecords6(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords6_Result>("GetWattsRecords6", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords7_Result> GetWattsRecords7(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords7_Result>("GetWattsRecords7", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForKitchen_Result> GetWattsRecordsForKitchen(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForKitchen_Result>("GetWattsRecordsForKitchen", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectDishwasherByUsernme1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectDishwasherByUsernme1", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForUser81(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForUser81", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHeatingAndCoolingAppliances_Result> GetWattsRecordsForHeatingAndCoolingAppliances(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHeatingAndCoolingAppliances_Result>("GetWattsRecordsForHeatingAndCoolingAppliances", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHomeEntertainmentAppliances_Result> GetWattsRecordsForHomeEntertainmentAppliances(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHomeEntertainmentAppliances_Result>("GetWattsRecordsForHomeEntertainmentAppliances", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SelectBathtubByUsernme1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SelectBathtubByUsernme1", usernameParameter);
        }
    
        public virtual int UpdateTotalWattsForBathtub1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalWattsForBathtub1", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForWaterAppliances1_Result> GetWattsRecordsForWaterAppliances1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForWaterAppliances1_Result>("GetWattsRecordsForWaterAppliances1", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForGasAppliances1_Result> GetWattsRecordsForGasAppliances1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForGasAppliances1_Result>("GetWattsRecordsForGasAppliances1", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForAlternateElectricity_Result> GetWattsRecordsForAlternateElectricity(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForAlternateElectricity_Result>("GetWattsRecordsForAlternateElectricity", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForKitchen1_Result> GetWattsRecordsForKitchen1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForKitchen1_Result>("GetWattsRecordsForKitchen1", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords8_Result> GetWattsRecords8(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords8_Result>("GetWattsRecords8", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecords9_Result> GetWattsRecords9(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecords9_Result>("GetWattsRecords9", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForKitchenResult_Result> GetWattsRecordsForKitchenResult(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForKitchenResult_Result>("GetWattsRecordsForKitchenResult", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForKitchenResults_Result> GetWattsRecordsForKitchenResults(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForKitchenResults_Result>("GetWattsRecordsForKitchenResults", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHeatingAndCoolingAppliance_Result> GetWattsRecordsForHeatingAndCoolingAppliance(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHeatingAndCoolingAppliance_Result>("GetWattsRecordsForHeatingAndCoolingAppliance", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHeatingAndCoolingAppliance1_Result> GetWattsRecordsForHeatingAndCoolingAppliance1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHeatingAndCoolingAppliance1_Result>("GetWattsRecordsForHeatingAndCoolingAppliance1", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHeatingAndCooling1_Result> GetWattsRecordsForHeatingAndCooling1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHeatingAndCooling1_Result>("GetWattsRecordsForHeatingAndCooling1", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHeatingAndCoolingAppliancesPage_Result> GetWattsRecordsForHeatingAndCoolingAppliancesPage(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHeatingAndCoolingAppliancesPage_Result>("GetWattsRecordsForHeatingAndCoolingAppliancesPage", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForHomeEntertainmentAppliance_Result> GetWattsRecordsForHomeEntertainmentAppliance(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForHomeEntertainmentAppliance_Result>("GetWattsRecordsForHomeEntertainmentAppliance", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForWaterAppliance_Result> GetWattsRecordsForWaterAppliance(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForWaterAppliance_Result>("GetWattsRecordsForWaterAppliance", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForGasAppliance_Result> GetWattsRecordsForGasAppliance(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForGasAppliance_Result>("GetWattsRecordsForGasAppliance", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForAlternateElectricityAppliancePage_Result> GetWattsRecordsForAlternateElectricityAppliancePage(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForAlternateElectricityAppliancePage_Result>("GetWattsRecordsForAlternateElectricityAppliancePage", usernameParameter);
        }
    
        public virtual ObjectResult<GetWattsRecordsForAlternateElectricityAppliancePages_Result> GetWattsRecordsForAlternateElectricityAppliancePages(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWattsRecordsForAlternateElectricityAppliancePages_Result>("GetWattsRecordsForAlternateElectricityAppliancePages", usernameParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
