//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz_Co2HomeServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AffilaiteLink
    {
        public int AfflilateLinkID { get; set; }
        public string Appliance { get; set; }
        public string Link { get; set; }
    }
}
