//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz_Co2HomeServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Category()
        {
            this.tbl_Barbecue = new HashSet<tbl_Barbecue>();
            this.tbl_Barbecue1 = new HashSet<tbl_Barbecue>();
            this.tbl_Bathtubr = new HashSet<tbl_Bathtubr>();
            this.tbl_Bathtubr1 = new HashSet<tbl_Bathtubr>();
            this.tbl_Bidet = new HashSet<tbl_Bidet>();
            this.tbl_Bidet1 = new HashSet<tbl_Bidet>();
            this.tbl_Computer = new HashSet<tbl_Computer>();
            this.tbl_Computer1 = new HashSet<tbl_Computer>();
            this.tbl_Cooktop = new HashSet<tbl_Cooktop>();
            this.tbl_Cooktop1 = new HashSet<tbl_Cooktop>();
            this.tbl_Dishwashere = new HashSet<tbl_Dishwashere>();
            this.tbl_Dryer = new HashSet<tbl_Dryer>();
            this.tbl_Electriccarcharger = new HashSet<tbl_Electriccarcharger>();
            this.tbl_Electriccarcharger1 = new HashSet<tbl_Electriccarcharger>();
            this.tbl_Faucet = new HashSet<tbl_Faucet>();
            this.tbl_Faucet1 = new HashSet<tbl_Faucet>();
            this.tbl_Fireplace = new HashSet<tbl_Fireplace>();
            this.tbl_Fireplace1 = new HashSet<tbl_Fireplace>();
            this.tbl_Freezer = new HashSet<tbl_Freezer>();
            this.tbl_Furnance = new HashSet<tbl_Furnance>();
            this.tbl_Furnance1 = new HashSet<tbl_Furnance>();
            this.tbl_GamingConsole = new HashSet<tbl_GamingConsole>();
            this.tbl_GamingConsole1 = new HashSet<tbl_GamingConsole>();
            this.tbl_GasDryer = new HashSet<tbl_GasDryer>();
            this.tbl_GasDryer1 = new HashSet<tbl_GasDryer>();
            this.tbl_GasOven = new HashSet<tbl_GasOven>();
            this.tbl_GasOven1 = new HashSet<tbl_GasOven>();
            this.tbl_Generator = new HashSet<tbl_Generator>();
            this.tbl_Generator1 = new HashSet<tbl_Generator>();
            this.tbl_healthiestlightbulbs = new HashSet<tbl_healthiestlightbulbs>();
            this.tbl_healthiestlightbulbs1 = new HashSet<tbl_healthiestlightbulbs>();
            this.tbl_Humidifier = new HashSet<tbl_Humidifier>();
            this.tbl_Humidifier1 = new HashSet<tbl_Humidifier>();
            this.tbl_Jacuzzi = new HashSet<tbl_Jacuzzi>();
            this.tbl_Jacuzzi1 = new HashSet<tbl_Jacuzzi>();
            this.tbl_Laptop = new HashSet<tbl_Laptop>();
            this.tbl_Laptop1 = new HashSet<tbl_Laptop>();
            this.tbl_Lawnsprinklersystem = new HashSet<tbl_Lawnsprinklersystem>();
            this.tbl_Lawnsprinklersystem1 = new HashSet<tbl_Lawnsprinklersystem>();
            this.tbl_Microwave = new HashSet<tbl_Microwave>();
            this.tbl_Modem = new HashSet<tbl_Modem>();
            this.tbl_Modem1 = new HashSet<tbl_Modem>();
            this.tbl_Outdoorsprinklersystem = new HashSet<tbl_Outdoorsprinklersystem>();
            this.tbl_Outdoorsprinklersystem1 = new HashSet<tbl_Outdoorsprinklersystem>();
            this.tbl_Oven = new HashSet<tbl_Oven>();
            this.tbl_Pool = new HashSet<tbl_Pool>();
            this.tbl_Pool1 = new HashSet<tbl_Pool>();
            this.tbl_Programmablethermostat = new HashSet<tbl_Programmablethermostat>();
            this.tbl_Programmablethermostat1 = new HashSet<tbl_Programmablethermostat>();
            this.tbl_Refrigilator = new HashSet<tbl_Refrigilator>();
            this.tbl_Router = new HashSet<tbl_Router>();
            this.tbl_Router1 = new HashSet<tbl_Router>();
            this.tbl_Shower = new HashSet<tbl_Shower>();
            this.tbl_Shower1 = new HashSet<tbl_Shower>();
            this.tbl_Showerhead = new HashSet<tbl_Showerhead>();
            this.tbl_Showerhead1 = new HashSet<tbl_Showerhead>();
            this.tbl_Sink = new HashSet<tbl_Sink>();
            this.tbl_Sink1 = new HashSet<tbl_Sink>();
            this.tbl_Smartphone = new HashSet<tbl_Smartphone>();
            this.tbl_Smartphone1 = new HashSet<tbl_Smartphone>();
            this.tbl_Smartpowerstrip = new HashSet<tbl_Smartpowerstrip>();
            this.tbl_Smartpowerstrip1 = new HashSet<tbl_Smartpowerstrip>();
            this.tbl_SmartSpeaker = new HashSet<tbl_SmartSpeaker>();
            this.tbl_SmartSpeaker1 = new HashSet<tbl_SmartSpeaker>();
            this.tbl_Solarpanels = new HashSet<tbl_Solarpanels>();
            this.tbl_Solarpanels1 = new HashSet<tbl_Solarpanels>();
            this.tbl_Stove = new HashSet<tbl_Stove>();
            this.tbl_Television = new HashSet<tbl_Television>();
            this.tbl_Television1 = new HashSet<tbl_Television>();
            this.tbl_Toilet = new HashSet<tbl_Toilet>();
            this.tbl_Toilet1 = new HashSet<tbl_Toilet>();
            this.tbl_WashingMachine = new HashSet<tbl_WashingMachine>();
            this.tbl_WaterAC = new HashSet<tbl_WaterAC>();
            this.tbl_WaterAC1 = new HashSet<tbl_WaterAC>();
            this.tbl_Waterdispenser = new HashSet<tbl_Waterdispenser>();
            this.tbl_Waterdispenser1 = new HashSet<tbl_Waterdispenser>();
            this.tbl_WaterHeater = new HashSet<tbl_WaterHeater>();
            this.tbl_WaterHeater1 = new HashSet<tbl_WaterHeater>();
            this.tbl_WRefrigilator = new HashSet<tbl_WRefrigilator>();
            this.tbl_WRefrigilator1 = new HashSet<tbl_WRefrigilator>();
        }
    
        public int CategoryID { get; set; }
        public string Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Barbecue> tbl_Barbecue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Barbecue> tbl_Barbecue1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bathtubr> tbl_Bathtubr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bathtubr> tbl_Bathtubr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bidet> tbl_Bidet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bidet> tbl_Bidet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Computer> tbl_Computer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Computer> tbl_Computer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cooktop> tbl_Cooktop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cooktop> tbl_Cooktop1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dishwashere> tbl_Dishwashere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dryer> tbl_Dryer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Electriccarcharger> tbl_Electriccarcharger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Electriccarcharger> tbl_Electriccarcharger1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Faucet> tbl_Faucet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Faucet> tbl_Faucet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Fireplace> tbl_Fireplace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Fireplace> tbl_Fireplace1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Freezer> tbl_Freezer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Furnance> tbl_Furnance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Furnance> tbl_Furnance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GamingConsole> tbl_GamingConsole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GamingConsole> tbl_GamingConsole1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GasDryer> tbl_GasDryer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GasDryer> tbl_GasDryer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GasOven> tbl_GasOven { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GasOven> tbl_GasOven1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Generator> tbl_Generator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Generator> tbl_Generator1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_healthiestlightbulbs> tbl_healthiestlightbulbs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_healthiestlightbulbs> tbl_healthiestlightbulbs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Humidifier> tbl_Humidifier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Humidifier> tbl_Humidifier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Jacuzzi> tbl_Jacuzzi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Jacuzzi> tbl_Jacuzzi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Laptop> tbl_Laptop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Laptop> tbl_Laptop1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Lawnsprinklersystem> tbl_Lawnsprinklersystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Lawnsprinklersystem> tbl_Lawnsprinklersystem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Microwave> tbl_Microwave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Modem> tbl_Modem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Modem> tbl_Modem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Outdoorsprinklersystem> tbl_Outdoorsprinklersystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Outdoorsprinklersystem> tbl_Outdoorsprinklersystem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Oven> tbl_Oven { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Pool> tbl_Pool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Pool> tbl_Pool1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Programmablethermostat> tbl_Programmablethermostat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Programmablethermostat> tbl_Programmablethermostat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Refrigilator> tbl_Refrigilator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Router> tbl_Router { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Router> tbl_Router1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Shower> tbl_Shower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Shower> tbl_Shower1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Showerhead> tbl_Showerhead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Showerhead> tbl_Showerhead1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sink> tbl_Sink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sink> tbl_Sink1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Smartphone> tbl_Smartphone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Smartphone> tbl_Smartphone1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Smartpowerstrip> tbl_Smartpowerstrip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Smartpowerstrip> tbl_Smartpowerstrip1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SmartSpeaker> tbl_SmartSpeaker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SmartSpeaker> tbl_SmartSpeaker1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Solarpanels> tbl_Solarpanels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Solarpanels> tbl_Solarpanels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stove> tbl_Stove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Television> tbl_Television { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Television> tbl_Television1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Toilet> tbl_Toilet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Toilet> tbl_Toilet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WashingMachine> tbl_WashingMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WaterAC> tbl_WaterAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WaterAC> tbl_WaterAC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Waterdispenser> tbl_Waterdispenser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Waterdispenser> tbl_Waterdispenser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WaterHeater> tbl_WaterHeater { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WaterHeater> tbl_WaterHeater1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WRefrigilator> tbl_WRefrigilator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WRefrigilator> tbl_WRefrigilator1 { get; set; }
    }
}
